CREATE TABLE PERFIL_USUARIO (
    ID             BIGINT NOT NULL,
    IS_ATIVO       BOOLEAN DEFAULT TRUE NOT NULL,
    DTH_INCLUSAO   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DTH_ALTERACAO  TIMESTAMP,
    NOME           VARCHAR(80) NOT NULL
);

ALTER TABLE PERFIL_USUARIO ADD CONSTRAINT PK_PERFIL_USUARIO PRIMARY KEY (ID);

INSERT INTO PERFIL_USUARIO (ID,IS_ATIVO,NOME) VALUES (1,TRUE,'ADMINISTRADOR');
INSERT INTO PERFIL_USUARIO (ID,IS_ATIVO,NOME) VALUES (2,TRUE,'SUPORTE');
INSERT INTO PERFIL_USUARIO (ID,IS_ATIVO,NOME) VALUES (3,TRUE,'CLIENTE');
INSERT INTO PERFIL_USUARIO (ID,IS_ATIVO,NOME) VALUES (4,TRUE,'SISTEMA');
