CREATE SEQUENCE SEQ_DOCUMENTO_DFE_ID;
                                
CREATE TABLE DOCUMENTO_DFE (
    ID                 BIGINT NOT NULL,
    ID_CONSULTA_DFE    BIGINT NOT NULL,
	RESP_SCHEMA        VARCHAR(40) NOT NULL,
	RESP_XML           BLOB SUB_TYPE 0 SEGMENT SIZE 16384,
	RESP_CHAVE_NFE     VARCHAR(60),
	RESP_EVENTO_ID     VARCHAR(60),
	RESP_NSU           VARCHAR(40),
	RESP_IE            VARCHAR(30),
	RESP_SIT_NFE       VARCHAR(30),
    CPF_CNPJ_EMITENTE  VARCHAR(20),
    NOME_EMITENTE      VARCHAR(150),
    VALOR_NOTA         NUMERIC(15,2),
    DTH_DOWNLOAD_XML   TIMESTAMP,
    IS_ATIVO           BOOLEAN DEFAULT TRUE NOT NULL,
    DTH_INCLUSAO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DTH_ALTERACAO      TIMESTAMP
);

ALTER TABLE DOCUMENTO_DFE ADD CONSTRAINT PK_DOCTO_DFE
    PRIMARY KEY (ID);

ALTER TABLE DOCUMENTO_DFE ADD CONSTRAINT FK_DOCTO_CONS_DFE_ID
    FOREIGN KEY (ID_CONSULTA_DFE) REFERENCES CONSULTA_DFE (ID);

