CREATE SEQUENCE SEQ_EMPRESA_ID;

CREATE TABLE EMPRESA (
    ID                    BIGINT NOT NULL,
    IS_ATIVO              BOOLEAN DEFAULT TRUE NOT NULL,
    DTH_INCLUSAO          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DTH_ALTERACAO         TIMESTAMP,
    NOME                  VARCHAR(80) NOT NULL,
    CPF_CNPJ              VARCHAR(20) NOT NULL,
    EMAIL                 VARCHAR(150) NOT NULL,
    CERT_BYTES            BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    CERT_SENHA            VARCHAR(500),
    CERT_DT_VALIDADE      DATE,
    ULT_NSU               VARCHAR(15),
    DTH_ULT_CONS_NFE      TIMESTAMP,
    UF_FISCAL             VARCHAR(2),
    AMBIENTE_NFE          VARCHAR(1),
    MANIFESTO_AUTOMATICO  BOOLEAN
);

ALTER TABLE EMPRESA ADD CONSTRAINT UQ_EMPRESA_CPF_CNPJ UNIQUE (CPF_CNPJ);
ALTER TABLE EMPRESA ADD CONSTRAINT UQ_EMPRESA_EMAIL UNIQUE (EMAIL);
ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA PRIMARY KEY (ID);

