CREATE SEQUENCE SEQ_SOLICITACAO_CONS_DFE_ID;

CREATE TABLE SOLICITACAO_CONS_DFE (
    ID                 BIGINT NOT NULL,
    ID_EMPRESA_DEST    BIGINT NOT NULL,
    ORIGEM_SOLICITACAO VARCHAR(1) NOT NULL,
    SITUACAO_ATUAL     VARCHAR(1) NOT NULL,
    MSG_RETORNO        VARCHAR(900),
    IS_ATIVO           BOOLEAN DEFAULT TRUE NOT NULL,
    DTH_INCLUSAO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DTH_ALTERACAO      TIMESTAMP
);

ALTER TABLE SOLICITACAO_CONS_DFE
    ADD CONSTRAINT PK_SOLICITACAO_CONS_DFE PRIMARY KEY (ID);

ALTER TABLE SOLICITACAO_CONS_DFE
    ADD CONSTRAINT FK_SOLICIT_CONS_DFE_ID_EMP_DEST FOREIGN KEY (ID_EMPRESA_DEST) REFERENCES EMPRESA (ID);

ALTER TABLE SOLICITACAO_CONS_DFE
    ADD CONSTRAINT CK_SOLICIT_CONS_DFE_ORIGEM CHECK (ORIGEM_SOLICITACAO IN ('M','A'));

ALTER TABLE SOLICITACAO_CONS_DFE
    ADD CONSTRAINT CK_SOLICIT_CONS_DFE_SIT CHECK (SITUACAO_ATUAL IN ('F','P'));

