CREATE SEQUENCE SEQ_CONSULTA_DFE_ID;
                                
CREATE TABLE CONSULTA_DFE (
    ID                 BIGINT NOT NULL,
    ID_EMPRESA_DEST    BIGINT NOT NULL,
    CPF_CNPJ_DEST      VARCHAR(20) NOT NULL,
    AMBIENTE_NFE       VARCHAR(01) NOT NULL,
    UF_FISCAL_DEST     VARCHAR(02) NOT NULL,
    ULT_NSU_CONS       VARCHAR(15) NOT NULL,
    ID_SOLICITACAO     BIGINT NOT NULL,
    IS_ATIVO           BOOLEAN DEFAULT TRUE NOT NULL,
    RESP_XML           BLOB SUB_TYPE 0 SEGMENT SIZE 16384,
    RESP_SOAP_XML      BLOB SUB_TYPE 0 SEGMENT SIZE 16384,
    RESP_STATUS        INTEGER,
    RESP_TXT_MOTIVO    VARCHAR(500),
    RESP_ULT_NSU       VARCHAR(15) NOT NULL,
    RESP_MAX_NSU       VARCHAR(15) NOT NULL,
    RESP_QTDE_DOCTOS   INTEGER,
    DTH_INCLUSAO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DTH_ALTERACAO      TIMESTAMP
);

ALTER TABLE CONSULTA_DFE ADD CONSTRAINT PK_CONS_DFE
    PRIMARY KEY (ID);

ALTER TABLE CONSULTA_DFE ADD CONSTRAINT FK_CONS_DFE_ID_EMP
    FOREIGN KEY (ID_EMPRESA_DEST) REFERENCES EMPRESA (ID);

ALTER TABLE CONSULTA_DFE ADD CONSTRAINT FK_CONS_DFE_ID_SOLICIT
    FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACAO_CONS_DFE (ID);
