CREATE SEQUENCE SEQ_USUARIO_ID;

CREATE TABLE USUARIO (
    ID             BIGINT NOT NULL,
    IS_ATIVO       BOOLEAN DEFAULT TRUE NOT NULL,
    DTH_INCLUSAO   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DTH_ALTERACAO  TIMESTAMP,
    NOME           VARCHAR(80) NOT NULL,
    LOGIN          VARCHAR(150) NOT NULL,
    SENHA          VARCHAR(500) NOT NULL,
    EMAIL          VARCHAR(150) NOT NULL,
    ID_PERFIL      BIGINT NOT NULL
);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID);

ALTER TABLE USUARIO ADD CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL);

ALTER TABLE USUARIO ADD CONSTRAINT UQ_USUARIO_LOGIN UNIQUE (LOGIN);

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_ID_PERFIL
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL_USUARIO (ID);

